kong-database:
    image: daocloud.io/koolay/alpine-postgres
    ports:
    - 5432:5432

kong:
    image: daocloud.io/koolay/kong
    links:
    - "pg"
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 7946:7946
    - 7946:7946/udp

